- INSTRUCTIONS.md
- minerva-core/src/main/java/org/geneontology/minerva/util/DebugTools.java
- minerva-core/src/main/java/org/geneontology/minerva/util/ParserWrapper.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3BatchHandler.java
- test.sh
- Adds a reasoner.dispose() call to the batch handler's cleanup code.
I tested the fix by running `test.sh` and then using the following `curl` command:
```
curl -v 'http://localhost:6800/m3BatchPrivileged?intention=action&requests=%5B%7B%22entity%22%3A%22model%22%2C%22operation%22%3A%22add%22%2C%22arguments%22%3A%7B%7D%7D%5D&uid=http%3A%2F%2Forcid.org%2F0000'
```
Without the dispose(), each `curl` request generates 8 Elk-Reasoner threads which are never released. With the dispose(), there are no Elk-Reasoner threads left around.
---
Additional changes with this PR, unrelated to the dispose() fix.
- Updates INSTRUCTIONS.md
- Adds DebugTools.logMemory() to print a message and the current free
memory.
- Adds a version of ParserWrapper that uses the catalog.xml to find local OWL models.
> - Adds a reasoner.dispose() call to the batch handler's cleanup code.

- minerva-converter/src/main/java/org/geneontology/minerva/GafToLegoIndividualTranslator.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/AbstractLegoTranslator.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/GafExportTool.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/GroupingTranslator.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/LegoModelWalker.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/LegoToGeneAnnotationTranslator.java
- minerva-converter/src/main/java/org/geneontology/minerva/taxon/FindTaxonTool.java
- minerva-converter/src/test/java/org/geneontology/minerva/evidence/FindGoCodesTest.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/LegoToGeneAnnotationTranslatorTest.java
- minerva-core/src/main/java/org/geneontology/minerva/FileBasedMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/MolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/curie/CurieHandler.java
- minerva-core/src/main/java/org/geneontology/minerva/curie/MappedCurieHandler.java
- minerva-core/src/main/java/org/geneontology/minerva/util/AnnotationShorthand.java
- minerva-core/src/test/java/org/geneontology/minerva/MolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/curie/DefaultCurieHandlerTest.java
- minerva-server/src/main/java/org/geneontology/minerva/ModelWriterHelper.java
- minerva-server/src/main/java/org/geneontology/minerva/generate/ModelSeeding.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelCreator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
This addresses #58. Tests pass on my machine, except for two reasoner tests that hit out of memory errors. These changes will throw an error if someone tries to enter a non-prefixed IRI or a prefixed IRI for which we don't have a prefix mapping. Noctua presents the error but it is a stack trace. Should this be made friendlier on the Minerva side?
> Added stricter handling for IRI creation.

- minerva-core/src/main/java/org/geneontology/minerva/util/AnnotationShorthand.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpSeedHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3BatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3SeedHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/MinervaResponse.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelCreator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchTestTools.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/DataPropertyTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelEditTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ParallelModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/SeedHandlerTest.java
This adds support for a list of user groups in requests, for https://github.com/geneontology/noctua/issues/350. It is not heavily tested so far, but I wanted to get it out to coordinate with Noctua UI development. The JSON property and HTTP parameter are both currently named `provided-by` (sound okay, @kltm?). I *believe* you provide multiple values simply by putting the same parameter into the query string multiple times, with different values.
> Implemented support for 'provided-by' annotation (user groups).

- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
correct implicit assumption that filenames in --lego-to-gpad have no suffix - default is now ttl
> fix for lego-to-gpad now we dump ttl

- .travis.yml
- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
- pom.xml
An official OWL API release is now available containing the bug fix related to #82. This pull request does not contain other changes in progress such as modifications to handling of empty external lookup service results. So, we should merge this change and deploy ASAP.
> Include triple reading-order fix from OWL API (release version)

- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
- minerva-core/src/main/java/org/geneontology/minerva/util/BlazegraphMutationCounter.java
This would be run after first stopping the Minerva server. Then you can use  Minerva to update the journal by specifying a file containing a SPARQL update:
```bash
./bin/minerva-cli.sh --sparql-update -j blazegraph.jnl -f delete_json.rq
```
or directly with the jar:
```bash
java -jar minerva-cli.jar --sparql-update -j blazegraph.jnl -f delete_json.rq
```
> Added command for running SPARQL update on an offline database.

- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/CachingInferenceProviderCreatorImpl.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/LocalServerTest.java
- pom.xml
To use Arachne instead of ELK, replace `--slme-elk` with `--arachne` in the startup command line.
> Support for use of Arachne as live reasoner in Noctua editor

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
This will probably initially provide more annotation extensions than desired, but I can add some filters after folks have a chance to review the output.
> Remove evidence requirements for annotation extensions in GPAD output.

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
Would we ever want has_part in annotation extensions?
> Remove has-part from whitelist

- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
- minerva-core/src/main/java/org/geneontology/minerva/curie/DefaultCurieHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/test/java/org/geneontology/minerva/ModelDecorationTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/LocalServerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelEditTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ParallelModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/SeedHandlerTest.java
Fixes #113.
Assumes that someone using a custom JSON-LD context will prepare a single file to pass to Minerva.
> Allow passing of custom JSON-LD context to StartUpTool.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
This addresses this Noctua issue: https://github.com/geneontology/noctua/issues/463
> Only allow root annotations in GPAD export if ND evidence.

- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
@cmungall I removed this requirement for 4 GB memory. The test seems to work fine with what Travis provides, which is 2 GB. It would be great to get Travis working so we start paying attention to failed builds.
> Removed constraint on available memory for test.

- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
- minerva-core/src/test/resources/mmg/basic-fullcycle-dump.ttl
* As requested in [this issue](https://github.com/geneontology/minerva/issues/143), I extended the BlazegraphMolecularModelManagerTest class to test a full blazegraph processing cycle, including dumping/importing models, adding/deleting individuals/facts, etc. 
* If any additional tests need to be included, please let me know. Thank you.
> Extending BlazegraphMolecularModelManagerTest to test the full processing cycle of Blazegraph

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/BasicGPADData.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/DefaultGPADData.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADData.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADOperatorStatus.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADRenderer.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-basic.rq
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/59d1072300000074.gpad
- minerva-converter/src/test/resources/59d1072300000074.ttl
It is a bit overdue but this branch extends the codes that generate GPAD in Minerva to include negations in the qualifier field of GPAD (See also: [issue #149](https://github.com/geneontology/minerva/issues/149)). Unittest codes and sample ttle files are also added to check whether negations are properly produced and recorded in GPAD files.
> Extend GPAD generation codes to support negations in the qualifier field of GPAD.

- minerva-core/src/main/resources/go_context.jsonld
Fixes #199. This was requested by MGI, although https://github.com/geneontology/go-site/issues/91 suggests that removing the `MGI`: doubling is desired eventually. I will open a separate PR to change https://github.com/prefixcommons/biocontext/blob/master/registry/go_context.jsonld.
> Remove “MGI:” from MGI prefix expansion. 

- pom.xml
This should fix a problem in returning explanations for owl:Nothing inferences in Noctua. go-plus currently contains the axiom `owl:Nothing SubClassOf owl:Nothing`. That also needs to be figured out.
> Update version of owl-to-rules to avoid 'indirect rules' for reflexive subclasses.

- .gitignore
- .travis.yml
- minerva-core/src/main/java/org/geneontology/minerva/json/InferenceProvider.java
- minerva-server/pom.xml
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3BatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/CachingInferenceProviderCreatorImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/InferenceProviderCreatorImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/ShexController.java
- minerva-server/src/main/resources/go-cam-shapes.shapeMap
- minerva-server/src/main/resources/go-cam-shapes.shex
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ParallelModelReasonerTest.java
Adds a shex validation step when the reasoner flag is on.  Look for information coming back in the response object:
response.data.unconformantFlag 
response.data.nonconformant_uris 
response.message 
Although the change is stuck in next to the reasoner process, it works independently.  e.g. it will still run when the model is inconsistent.  This works because it gets superclass information from a sparql query to rdf.geneontology.org .  If we changed the schema to look at types on individuals with the expectation that they would be fully expanded, then we could read those in from the reasoner without the external call.  (Noting that Arachne does not provide subclass expansion, just node typing).  It also downloads the schema from the GO_Shapes repository on startup, hence it needs net …
> Shex validation

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/ModelContainer.java
- minerva-core/src/main/java/org/geneontology/minerva/json/InferenceProvider.java
- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
- minerva-core/src/main/java/org/geneontology/minerva/server/validation/ModelValidationReport.java
- minerva-core/src/main/java/org/geneontology/minerva/util/JenaOwlTool.java
- minerva-json/src/main/java/org/geneontology/minerva/json/JsonOwlIndividual.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3BatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/CachingInferenceProviderCreatorImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/InferenceProviderCreatorImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/ShexController.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ModelValidationReport.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/OWLValidationReport.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexConstraint.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexExplanation.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexValidationReport.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexValidationResult.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexValidator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexViolation.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/Violation.java
this contains a bunch of re-organization.  Other noteworthy changes:
Now using reasoned ontology loaded at startup to get superclasses for shex - no more dependency on external sparql.  
Filled in everything in the shex validation response with real data (URIs) with the exception of the property constraints that were violated (still figuring out how to get to those).  
Added complete super type information to individuals in the response.  From this the client could e.g. get root types without any other call.
> Issue 212 validation service response

- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/UndoAwareMolecularModelManager.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
This work is in reference to https://github.com/geneontology/pathways2GO/issues/71
This allows entity ontologies aside from neo to be used to construct go-cams while maintaining GPAD outputs that adhere strictly to canonical terminologies such as UniProt for human genes.  It works by adding the annotation property  http://geneontology.org/lego/canonical_record to link new terms (e.g. reactome entities) to canonical terms (e.g. corresponding uniprots).  When these annotations are present, the GPAD SPARQL export process begins by converting the model to one with all of the external types replaced by canonical types.  The rest of the gpad export process is then unchanged.
> implements pattern for retrieving canonical identifiers in gpad output

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/main/resources/ModelSearchQueryTemplate.rq
If &count is added to any request, the result will be empty except for n = number of results for the query.  
This is a separate request from the normal query because it would require two hits to the server anyway and is not always needed.  ping @tmushayahama
> adding result count request paramater #235 and #230 

- .gitignore
- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/MinervaShexValidator.java
build-cli.sh 
export MINERVA_CLI_MEMORY=12g 
bin/minerva-cli.sh --owlcheck-go-cams -i ../test/resources/gocam/ -c ../test/catalog-v001-for-noctua.xml --output-file ../test/basic_output.txt
output: 
filename model_id OWL_consistent shex_valid
test-membrane.ttl http://model.geneontology.org/R-HSA-4641262 true true 
test-DVL.ttl http://model.geneontology.org/R-HSA-201688 true false
> Owl cmdline issue254

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidationReport.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-lookup/src/main/java/org/bbop/golr/java/AbstractRetrieveGolr.java
- minerva-lookup/src/main/java/org/bbop/golr/java/RetrieveGolrOntologyClass.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/CachingExternalLookupService.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/CombinedExternalLookupService.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/ExternalLookupService.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/GolrExternalLookupService.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/MonarchExternalLookupService.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/TableLookupService.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/InferenceProviderCreatorImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/MinervaShexValidator.java
This PR combines changes to the GOLR requests (POSTing single batch requests per model rather than multiple GETs) and an extension to the shex validation service that effectively CLOSEs the shapes listed in our shape map.  Also amended shex validation service such that all elements that were URIs are now Curies.
> Performance go shapes199

- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
Since last fall, Minerva has been sending the full closure of types (all superclasses of each type associated with an instance) in the json response whenever the reasoner is on.  I thought this might be useful, but I don't think it is being used by anyone and it is really slowing down the response time when the reasoner is on.  
This commit takes that out of the response resulting in significant speed improvement.  If we want to add it back in, we should be more clever about limiting the types served up to only those needed by applications.  
If you are okay with this, lets merge and include with bug fix from earlier tonight.
> take out all super types from response.  rendering took forever

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
If this is alive http://skyhook.berkeleybop.org/blazegraph-go-lego-reacto-neo.jnl.gz
this should work
> change ontojournal location

- minerva-converter/src/test/resources/go-lego-module.omn
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
- minerva-server/src/test/resources/validate.shex
fixes problem detected in https://github.com/geneontology/minerva/pull/313
resulting from lack of inference step applied to go-lego including neo.  That found that PR_000000001 was equivalent to CHEBI_36080 .  All reference in minerva code now use the chebi uri.
> changing all root protein to chebi reference

- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/MolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/UndoAwareMolecularModelManagerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/DataPropertyTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/LocalServerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelEditTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ParallelModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/TaxonHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/validation/ValidationTest.java
This ought to go into that config file and not get spread all over..  Someday will do that.  For now just avoiding the likely conflict.  
Regarding:  https://github.com/geneontology/minerva/pull/316#issuecomment-623770972
> removing /tmp/blazegraph.jnl references

- minerva-core/src/main/java/org/geneontology/minerva/model/GoCamModel.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-core/src/test/resources/validation/go-cam-shapes.shex
- minerva-server/src/test/resources/validate.shex
this is an improvement to the shex validator.  it will now correctly fail validation when property assertions are added that are not specified in the Shex Shape corresponding to rdf type of the node being validated.  
there is also a bug fix that should clean up some of the cascading errors when something does not validate.
> Shex closed impl bug fix

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/ExportExplanation.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
The explanation service was using the Golr ExternalLookupService .  This is no longer operational within minerva.  It was replaced by the local blazegraph ontology manager - here for label lookups.  ExternalLookupService references and code could be removed from the code base - assuming the blazegraphontologymanager pattern is kept.  cc @balhoff
> fixes #360

- minerva-cli/pom.xml
a) see compatibility chart https://github.com/git-commit-id/git-commit-id-maven-plugin
b) with this version  we can build minerva-cli when using docker build.
> using git-commit-plugin that is compatible with java8

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-server/.gitignore
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelARTHandler.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ARTHandlerTest.java
- minerva-server/src/test/resources/models/art-simple/gp-mf-simple.ttl
@lpalbou and I worked on making temporary stored model api until diff as per this comment https://github.com/geneontology/minerva/issues/364
This is to show sample code. This is a working art api to get the stored model
The approach of separate API doesn't cause any side effect as it is readonly and easy to extend without hustles. It uses the same concept as searchAPI with jetty. Take a look how it is decoupled with m3Batch
to get the store endpoint is
from minerva http://localhost:6800/search/stored?id=gomodel:5fdc2fda00000000
from barista http://localhost:3400/search/stored?id=gomodel:5fdc2fda00000000
reason for search endpoint is temporary testing as barista only allows search proxy
tagging @lpalbou  @balhoff @kltm
> Added ART for stored model

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
Use aggregates for everything else, in order to align number of results returned with the number of matching models. Addresses #370
> GROUP BY only model id.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
> Close output streams when dumping files.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/no_uberon_with_emapa.ttl
> Suppress UBERON annotation extensions when an EMAPA structure is present.

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
> Don’t filter out GPAD annotations for 'do not annotate' violations.

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/test_filter_regulated_process.ttl
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/main/resources/org/geneontology/minerva/regulation_targets.rq
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
Exclude annotations to a regulated term when there is also an annotation to a regulation of that term, for a particular gene product instance. See #394.
> Exclude annotations to regulated terms

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidationReport.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
This came out of a request by @ukemi for OWL consistency checks to be run on the MGI import models. But since we're still working on a [ShEx validator bug](https://github.com/geneontology/minerva/issues/399) exposed in these models, my attempt to bypass `--shex` in `--validate-go-cams` (and thus only running OWL checks) didn't seem to be working. ShEx checks were still performed and eventually broke on a model due to aforementioned [validator issue](https://github.com/geneontology/minerva/issues/399).
This PR is to allow validation w/o ShEx, which I know is not the desired attitude in the MOD imports project but this was necessary to get out the OWL checks. So, up to you @balhoff if you want to merge this "feature".
> Allow skipping ShEx in --validate-go-cams when --shex is omitted

- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-core/src/test/java/org/geneontology/minerva/validation/ShexValidatorTest.java
- minerva-core/src/test/resources/validation/model_test/ZFIN_ZDB-GENE-030131-514.ttl
> Fixes for handling negations in ShEx validation

- minerva-cli/pom.xml
- minerva-server/pom.xml
- pom.xml
> Add log4j-core; update to log4j 2.16.0

- minerva-cli/pom.xml
- minerva-cli/src/main/resources/log4j.properties
- minerva-cli/src/main/resources/log4j2.xml
- minerva-server/pom.xml
- minerva-server/src/main/resources/log4j.properties
- minerva-server/src/main/resources/log4j2.xml
I realized that log4j 2.x requires a different config file format. However part of Blazegraph seems to independently load the old properties format, so I have left that in place as well.
> Add log4j xml config

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/MolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/UndoAwareMolecularModelManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/MolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/UndoAwareMolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/model/GoCamModelTest.java
- minerva-core/src/test/java/org/geneontology/minerva/validation/ShexValidatorTest.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ARTHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/DataPropertyTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/LocalServerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelEditTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ParallelModelReasonerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/TaxonHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/validation/ValidationTest.java
> Automatically load tbox into ontojournal for GPAD export command.

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsTools.java
For #500.
@kltm here's a quick implementation if you want to try while I'm away. It's a bit slow. The command line would be:
```
./minerva-cli/bin/minerva-cli.sh --dump-owl-json --journal blazegraph.jnl --ontojournal blazegraph-go-lego-reacto-neo.jnl --folder jsonout
```
> Add command to dump models to JSON files.

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
@alexsign @vanaukenk removing [involved in](http://purl.obolibrary.org/obo/RO_0002331) from GPAD extensions output.
> Remove 'involved in' from allowed extensions relations

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
Leaving the CARO root type for now. For https://github.com/geneontology/go-ontology/issues/25485.
> Replace CARO anatomical entity with Uberon.

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
New CLI option `--check-graph-type`. Fixes #541.
> Add cli option to allow running checks against a graphstore journal.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADRenderer.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/MGI_MGI_2429397.ttl
> Output interacting taxon in correct column.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/MolecularModelManagerTest.java
- minerva-core/src/test/resources/test-model-taxon-annotations.ttl
- minerva-core/src/test/resources/validation/should_pass/test-multi-org-1.ttl
- minerva-lookup/src/test/java/org/geneontology/minerva/lookup/GolrExternalLookupServiceTest.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelCreator.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelEditTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
- minerva-server/src/test/resources/edit-test/test-model-taxon-annotations.ttl
- minerva-server/src/test/resources/models/should_pass/test-multi-org-1.ttl
> Maintain correct set of in_taxon model annotations.
