- minerva-core/src/main/java/org/geneontology/minerva/UndoAwareMolecularModelManager.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelCreator.java
This should address https://github.com/geneontology/noctua/issues/373 and https://github.com/geneontology/noctua/issues/100.
> Disallow undo of initial annotations.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
This is a workaround to address https://github.com/geneontology/go-site/issues/265 caused by https://github.com/owlcs/owlapi/issues/574.
> Workaround to address missing production folder in GAF conversions

- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
- minerva-server/src/main/java/org/geneontology/minerva/ModelWriterHelper.java
- minerva-server/src/test/java/org/geneontology/minerva/ModelDecorationTest.java
These changes address #85 and #38.
@kltm I need to get some help running the latest Noctua locally, so I haven't been able to test this live. Perhaps you could try it out, or help me with GitHub auth for my dev environment (or both!).
> Removes json-model annotations from models

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
And a couple of small related updates.
> Enabled inferred GPAD output from Noctua UI.

- minerva-core/src/main/resources/amigo_context_manual.jsonld
attempt to feex geneontology/noctua#467
> attempt to add xenbase to jsonld context

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
See https://github.com/geneontology/noctua-models/issues/44
> Add regulates_o_occurs_in to whitelist

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
Just implemented this; about to test locally.
> Changed model import to load RDF direct into Blazegraph

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-relation-evidence-multiple.rq
Fixes https://github.com/geneontology/noctua/issues/410.
> Concatenate multiple sources on a single evidence.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
> Use group shorthand for assigned-by.

- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
> Throw exception rather than create a GPAD for an inconsistent ontology.

- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
> Remove commas from underscore property names.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
> Disallow equivalent conjunctive expressions in sets.

- minerva-cli/src/main/java/org/geneontology/minerva/cli/MinervaCommandRunner.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
@kltm I implemented this but not totally sure this shouldn't instead be a SPARQL update migration that is periodically run. What do you think?
> Don't load models with 'delete' modelstate.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/SPARQLGraphMessageBodyWriter.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/SPARQLHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/SPARQLResultsMessageBodyWriter.java
Fixes #93. This queries the database directly. It will not know about changes that have not been saved.
> Implemented SPARQL endpoint service.

- minerva-core/src/main/java/org/geneontology/minerva/json/InferenceProvider.java
- minerva-core/src/main/java/org/geneontology/minerva/server/validation/ValidationResultSet.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3BatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ModelValidationReport.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexConstraint.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexExplanation.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexValidationReport.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexValidator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ShexViolation.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/ValidationResultSet.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/Violation.java
Looks like this:
```json
"violations": [
{
"explanations": [
{
"shape_id": "http://purl.obolibrary.org/obo/go/shapes/MolecularFunction",
"constraints": [
{
"target_node_uri": "http://model.geneontology.org/R-HSA-73930/R-HSA-73930",
"property_id": "http://purl.obolibrary.org/obo/RO_0002413",
"intended_range_shapes": [
"http://purl.obolibrary.org/obo/go/shapes/MolecularFunction"
]
}
]
}
],
"node_id": "http://model.geneontology.org/R-HSA-73930/R-HSA-110360",
"commentary": "http://model.geneontology.org/R-HSA-73930/R-HSA-110360 did not match http://purl.obolibrary.org/obo/go/shapes/MolecularFunction"
}
]
}
],
```
> Added explanations for core shape failures

- minerva-lookup/src/main/java/org/bbop/golr/java/RetrieveGolrOntologyClass.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/GolrExternalLookupService.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/MonarchExternalLookupService.java
See https://github.com/geneontology/minerva/pull/261
> switched to isa_closure for golr query

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-cli/src/main/java/org/geneontology/minerva/cli/TypeUpdater.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexConstraint.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidationReport.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-lookup/src/main/java/org/geneontology/minerva/lookup/ExternalLookupService.java
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/InferenceProviderCreatorImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/inferences/MapInferenceProvider.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/MinervaShexValidator.java
Can run from the minerva command line as it sits.  Most likely not useful code once we are done here.  Could run it off a branch or merge it in and consider removing it later.  or just leave it in.. not harmful.   example from minerva-cli
--update-gene-product-types -i /Users/bgood/Documents/GitHub/noctua-models/models/ -o /Users/bgood/test/typed_master/ -n /Users/bgood/gocam_ontology/neo_full_nov20_2019.owl -c /Users/bgood/gocam_ontology/catalog-no-import.xml
> for step 4 in #260

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
cured an issue where repeated identical searches produced differently ordered results.
> fix ordering for model search

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
addressses https://github.com/geneontology/minerva/issues/230#issuecomment-579406266
> fix search result for users and groups

- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
https://github.com/geneontology/go-shapes/issues/197#issuecomment-583902491
> addressing shape inheritance issue

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
Fixed bug referencing development environment path..
> Performance go shapes199

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/ShexValidator.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
- minerva-server/src/main/java/org/geneontology/minerva/server/validation/MinervaShexValidator.java
yet another error introduced - here for shex validator.  going to merge as this will break go_shapes travis..
> fixing error running command line

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
Should act the same as GET but consumes APPLICATION_FORM_URLENCODED
> implemented POST

- .travis.yml
- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
Looking at this as a start on ways to test everything (e.g. to avoid cases where a developer like me hard codes an absolute file system path).  
Could be much more clever if we thought it was worth it.  e.g. actually run a series of commands and check on expected output.  This just checks to see if the command line will run the blazegraph import as a start..
> running command line client as part of travis.

- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/StatusHandler.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/LocalServerTest.java
Baseline system setup report is available at /status
> Status service 282

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/pipeline/BatchPipelineValidationReport.java
- minerva-core/src/main/java/org/geneontology/minerva/validation/pipeline/ErrorMessage.java
> Add pipeline report to cmdline validation

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
Added explanation for parameter parse fail based on ordering.
Added explicit exit codes for parse exceptions to signal shell of death.
> hopefully improved clarity of command line usage

- minerva-core/src/main/java/org/geneontology/minerva/MinervaOWLGraphWrapper.java
note to self need to revisit OWLGraphWrapper in light of new pattern for dealing with tbox.  dogs breakfast in there.
> think bug dead

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/TaxonHandler.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/TaxonHandlerTest.java
think this should fix issue #311
> changing routes for search service

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
address geneontology/noctua#670
> have tbox in manager when loading model from blazegraph

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
- minerva-json/src/main/java/org/geneontology/minerva/json/JsonOwlIndividual.java
- minerva-lookup/src/test/java/org/geneontology/minerva/lookup/GolrExternalLookupServiceTest.java
added methods to get the root types
changed how labels are gathered for ontology classes from many requests to one per model.
believe this should fix https://github.com/geneontology/minerva/issues/325
> added root-type to default m3batch response

- minerva-core/src/test/resources/validation/should_fail/test-multi-org-1-notitle.ttl
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/main/resources/ModelSearchQueryTemplate.rq
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
- minerva-server/src/test/resources/models/should_fail/test-multi-org-1-notitle.ttl
> add search by model id

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
fixes https://github.com/geneontology/minerva/issues/333#issuecomment-662044897
> allow for multiple ids in search

- minerva-core/src/main/java/org/geneontology/minerva/json/MolecularModelJsonRenderer.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
addressing https://github.com/geneontology/minerva/issues/339#issuecomment-663169069
> adding root types for partial model responses 

- minerva-core/pom.xml
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/JsonOrJsonpBatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/M3BatchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/OperationsImpl.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelEditTest.java
- minerva-server/src/test/java/org/geneontology/minerva/server/handler/ModelSearchHandlerTest.java
think this does it for #348 #355 
some iteration needed for response structure for #356  but the pattern is there now. 
Not sure if you want to wait on a more complete #356 or merge now.
> Modification state handling ART

- minerva-server/src/main/resources/ModelSearchQueryTemplate.rq
See https://github.com/geneontology/minerva/issues/370#issuecomment-797857166 and https://github.com/geneontology/minerva/pull/372#issuecomment-797856842
> Fix mismatch in date variable so that ordering works.

- INSTRUCTIONS.md
- minerva-converter/pom.xml
- minerva-core/pom.xml
- minerva-lookup/pom.xml
- minerva-server/pom.xml
- pom.xml
1. changed config for javadoc plugin so that we do not have to use -Dmaven.javadoc.skip=true
2. added jacoco plugiin
> added support for sonarqube

- minerva-server/src/main/java/org/geneontology/minerva/server/handler/ModelSearchHandler.java
> Return all matching individuals in search 

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/DefaultGPADData.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADData.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADEvidence.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADRenderer.java
- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-relation-evidence-multiple.rq
> Export creation-date and modification-date annotation properties in GPAD.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/test_root_mf_filter.ttl
> Don't create root MF annotation when root BP annotation is present

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/test_root_mf_filter2.ttl
- minerva-lookup/src/test/java/org/geneontology/minerva/lookup/GolrExternalLookupServiceTest.java
Addresses https://github.com/geneontology/minerva/issues/396#issuecomment-914506968.
> Allow both root MF and BP if different OWL instances.

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-relation-evidence-multiple.rq
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/created-date-test.ttl
> Retrieve created and imported dates from axiom annotations.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
> Don’t output import-date in GPAD.

- minerva-converter/src/main/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLExport.java
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/test_root_mf_filter3.ttl
- minerva-lookup/src/test/java/org/geneontology/minerva/lookup/GolrExternalLookupServiceTest.java
> Filter out root MF annotations if any other MF annotation exists for the GP.

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-relation-evidence-multiple.rq
- minerva-converter/src/test/java/org/geneontology/minerva/legacy/sparql/GPADSPARQLTest.java
- minerva-converter/src/test/resources/created-date-test.ttl
> Retrieve creation date from evidence node.

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
> Remove 'has participant' as valid extension relation

- minerva-server/pom.xml
- minerva-server/src/main/java/org/geneontology/minerva/server/StartUpTool.java
- minerva-server/src/main/java/org/geneontology/minerva/server/handler/StatusHandler.java
> Include git revision and ontology version IRI in status service.

- minerva-core/src/main/resources/obo_context.jsonld
See https://github.com/geneontology/minerva/issues/456#issuecomment-1079004785.
> Add PCL prefix expansion.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
> Add biological phase to root types.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphMolecularModelManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphMolecularModelManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/MolecularModelManagerTest.java
> Dump model on each save.

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
> Remove 'enabled by' as an extension relation

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-lookup/src/test/java/org/geneontology/minerva/lookup/GolrExternalLookupServiceTest.java
For https://github.com/geneontology/go-fastapi/issues/114.
> Pass provided ontology to command-line JSON dump.

- pom.xml
> GH-553 Upgrade jacoco maven plugin so that test run on jdk21

- minerva-core/src/main/resources/amigo_context_gen.jsonld
- minerva-core/src/main/resources/go_context.jsonld
For https://github.com/geneontology/noctua/issues/952.
> Update EcoCyc prefix expansion

- minerva-cli/src/main/java/org/geneontology/minerva/cli/CommandLineInterface.java
- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
- minerva-core/src/main/java/org/geneontology/minerva/CoreMolecularModelManager.java
- minerva-core/src/test/java/org/geneontology/minerva/BlazegraphOntologyManagerTest.java
- minerva-core/src/test/java/org/geneontology/minerva/validation/ShexValidatorTest.java
For https://github.com/geneontology/noctua/issues/981
> Load ontology into journal before initializing lookup maps.

- minerva-core/src/main/java/org/geneontology/minerva/BlazegraphOntologyManager.java
> Only retrieve taxon constraints from MacromolecularMachine classes

- minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq
> Don't allow GO root terms to be extensions

- minerva-core/src/main/resources/org/geneontology/minerva/ro-gpad.ofn
> Add property chain 'part of' o enables -> 'contributes to'

- minerva-core/src/main/resources/org/geneontology/minerva/ro-gpad.ofn
> Add additional property chains for parts of complexes
